version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    container_name: symfony_php

  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    container_name: symfony_nginx

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: symfony_db

volumes:
  pgdata:
